# Generated by Django 5.1.5 on 2025-04-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_checker', '0002_alter_coupon_code_coupon_unique_coupon_per_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponreport',
            name='status',
            field=models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid')], default='valid', max_length=10),
        ),
    ]
