# Generated by Django 5.1.5 on 2025-04-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_checker', '0003_couponreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponreport',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
