# Generated by Django 5.1.5 on 2025-04-17 11:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_checker', '0004_alter_couponreport_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponreport',
            name='checked_country',
            field=models.ForeignKey(default=uuid.UUID('3960b6d0-de72-4906-83bf-32d95efe674d'), on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='coupon_checker.country'),
        ),
    ]
