# Generated by Django 5.1.5 on 2025-04-17 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_checker', '0005_couponreport_checked_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponreport',
            name='checked_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='coupon_checker.country'),
        ),
    ]
