# Generated by Django 5.1.5 on 2025-04-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_checker', '0007_alter_couponreport_checked_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponreport',
            name='product_link',
            field=models.URLField(max_length=500),
        ),
    ]
