# Generated by Django 5.1.5 on 2025-04-22 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_checker', '0009_alter_couponreport_product_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='coupon_checker.company'),
        ),
    ]
